version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: harvitt
      POSTGRES_PASSWORD: harvitt36963
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://harvitt:harvitt36963@postgres:5432/school
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: >
      sh -c "
      npx prisma migrate dev --name init &&
      npm run start
      "

volumes:
  postgres_data:
